server:
  port : 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
#  security:
#    user:
#      name: test
#      password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 638851664417-h1pn88a5v3p58pcfchqhqbj5efj7qv7h.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: S6k_M340OVMV0xSnLg2H
            client-secret: OEXvv1YUls
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: authorization_code
            redirect-uri: http://localhost:8001/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.c7ypvotajcxo.ap-northeast-2.rds.amazonaws.com:3306/burgerking?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries-true
    username: admin
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
        
    
mybatis:
  mapper-locations:
  - /mappers/*.xml   

file:
  path: /Users/smile/Desktop/ms/ms/ms/workspace/security.miso/security.miso/upload/ 
